#!/bin/bash
# This is some secure program that uses security.

user=$USER
myconfig=$(pwd)/myconfig/
log_file=$(pwd)/log/
baselog="${log_file}"/base.log
errorlog="${log_file}"/error.log
defaultuser=""
list_package=(xorg xserver-xorg-core xserver-xorg-video-all openbox menu obconf obmenu lightdm sudo lxsession)

cat /dev/null > "$baselog"
cat /dev/null > "$errorlog"

msg() {
    echo "$1" | tee -a "$baselog"
}

confirm() {
	msg "$1 (y/n)"; read answer;
	if [ "$answer" == "y" ]; then	
		return 1
	elif [ "$answer" == "n" ]; then
		return 0
	elif [ -z "$answer" ] || [ "$answer" != "n" ] || [ "$answer" != "y" ]; then
		confirm "$1"
	fi
}

[[ $user = root ]] || {  msg "$user: Must be root!!" >&2; exit 1; }

msg "######################## INSTALL base ########################"
echo "Set default for user"; read defaultuser

sudo chown "$defaultuser":"$defaultuser" -R $(pwd)

confirm "edit source list?" || {
	msg "######################## sources.list ########################"
	msg "--add-architecture i386"
		dpkg --add-architecture i386
	msg "edit sources.list"
		cat "${myconfig}"sources.list > /etc/apt/sources.list
	msg "apt-get update"
		apt-get update 
	msg "apt-get dist-upgrade"
		apt-get dist-upgrade
	msg "######################## sources.list ########################"
}
confirm "Do you install list package" || {
	msg "#################### Install list_package ####################"
		for i in "${list_package[@]}"; do
			msg "Install $i"
			apt-get --yes install "$i" &>>"$baselog"
		done
	msg "################## End install list_package ##################"
}

confirm "Do you add any user to sudouser" || {
	msg "##################### ADDUSER to sudo ########################"
		adduser "$defaultuser" sudo
	msg "################## $defaultuser add sudo #####################"
}

confirm "Do you set default user in lightdm" || {
	msg "################### Set default to lightdm ###################"
	msg "set lightdm.conf"
		sed 's/usernamevariable/'"$defaultuser"'/' "${myconfig}"my-lightdmconfig > /etc/lightdm/lightdm.conf
		cat /etc/lightdm/lightdm.conf >> "$baselog"
	msg "#################### Add user to lightdm #####################"
}

confirm "Add synaptic to xorg.conf.d" || {
	msg "########################## Synaptic ##########################"
	msg "Make dir /etc/X11/xorg.conf.d"
		mkdir /etc/X11/xorg.conf.d 2>"$errorlog"
	msg "Make synaptics.conf"
		cat "${myconfig}"synaptics.conf > /etc/X11/xorg.conf.d/synaptics.conf
	msg "######################## Add Synaptic ########################"
}

confirm "install b43-fwcutter" || {
	msg "####################### b43-fwcutter #########################"
		apt-get --yes install b43-fwcutter &>>"$baselog"
		FIRMWARE_INSTALL_DIR="/lib/firmware"
		wget http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2
		tar xjf broadcom-wl-5.100.138.tar.bz2
		b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" broadcom-wl-5.100.138/linux/wl_apsta.o
	msg "##################### end b43-fwcutter #######################"
}