#!/bin/bash

source variable

cat /dev/null > "$baselog"
cat /dev/null > "$errorlog"

if test $USER != "root"; then
	msg "$USER: Must be root!!" >&2
	exit 1
fi

if [ ! -d "$PWD/downloads" ]; then
	mkdir -p "$PWD/downloads"
fi

msg "
######################## INSTALL base ########################
"

echo "Set default for user"; read defaultuser

if confirm "edit source list?"; then
	msg "######################## sources.list ########################"
	msg "--add-architecture i386"
		dpkg --add-architecture i386
	msg "edit sources.list"
		cat "${myconfig}"sources.list > /etc/apt/sources.list
	msg "apt-get update"
		apt-get update 
	msg "apt-get dist-upgrade"
		apt-get dist-upgrade
	msg "######################## sources.list ########################"
fi

if confirm "Do you add any user to sudouser"; then
	msg "##################### ADDUSER to sudo ########################"
		adduser "$defaultuser" sudo
	msg "################## $defaultuser add sudo #####################"
fi

if confirm "Do you set default user in lightdm"; then
	msg "################### Set default to lightdm ###################"
	msg "set lightdm.conf"
		sed 's/usernamevariable/'"$defaultuser"'/' "$myconfig/lightdm.config" > /etc/lightdm/lightdm.conf
	msg "#################### Add user to lightdm #####################"
fi

if confirm "Add synaptic to xorg.conf.d"; then
	msg "########################## Synaptic ##########################"
	msg "Make dir /etc/X11/xorg.conf.d"
		mkdir /etc/X11/xorg.conf.d 2>"$errorlog"
	msg "Make synaptics.conf"
		cat "${myconfig}"synaptics.conf > /etc/X11/xorg.conf.d/synaptics.conf
	msg "######################## Add Synaptic ########################"
fi 

if confirm "install b43-fwcutter"; then
	msg "####################### b43-fwcutter #########################"
		apt-get --yes install b43-fwcutter 2>>"$errorlog"
		FIRMWARE_INSTALL_DIR="/lib/firmware"
		wget -P "$PWD/downloads" http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2
		tar -xjf "$PWD/downloads/broadcom-wl-5.100.138.tar.bz2" -C "$PWD/downloads"
		b43-fwcutter -w "$FIRMWARE_INSTALL_DIR" "$PWD/downloads/broadcom-wl-5.100.138/linux/wl_apsta.o"
	msg "##################### end b43-fwcutter #######################"
fi
