#!/bin/bash

source variable

remove_package=(leafpad lxterminal xarchiver pcmanfm)
install_package=(gdebi xfce4-power-manager vlc conky clipit catfish disk-manager transmission-gtk nitrogen libgl1-mesa-swx11 redshift alsa-base alsa-utils lxappearance file-roller geany thunar-volman thunar-thumbnailers ffmpegthumbnailer thunar-archive-plugin thunar-media-tags-plugin terminator gmrun htop xfce4-screenshooter ttf-dejavu ttf-mscorefonts-installer gparted xfce4-volumed pulseaudio icedove flashplugin-nonfree curl)

msg "
###################### INSTALL base 2 #########################
"

if confirm "Do you remove package"; then
	msg "###################### Remove package  ########################"
		for i in "${remove_package[@]}"; do
			msg "Remove $i"
			sudo apt-get --yes remove --purge "$i" 2>>"$errorlog"
			msg "Purge $i"
			sudo apt-get --yes purge "$i" 2>>"$errorlog"
		done
	msg "##################### End remove package ######################"
fi

if confirm "Do you install install_package package"; then
	msg "################### Install install_package ###################"
		for i in "${install_package[@]}"; do
			msg "Install $i"
			sudo apt-get --yes install "$i" 2>>"$errorlog"
			msg "Build-dep $i"
			sudo apt-get --yes build-dep "$i" 2>>"$errorlog"
		done
	msg "################# End install install_package #################"
fi

if confirm "Add conkyrc"; then
	msg "########################### Conky ############################"
	msg "Make .conkyrc"
		mkdir -p "$PWD/downloads/harmattan"
		wget -P "$PWD/downloads" http://fc07.deviantart.net/fs71/f/2014/013/2/8/conky_harmattan_by_zagortenay333-d720use.zip
		file-roller -e "$PWD/downloads/harmattan" "$PWD/downloads/conky_harmattan_by_zagortenay333-d720use.zip"
		cp -R -t "$HOME" "$PWD/downloads/harmattan/.conky-weather"
		cat "$myconfig/conkyrc" > "$HOME/.conkyrc"
	msg "######################### End Conky ##########################"
fi

if confirm "Set openbox rc.xml"; then
	msg "########################## Openbox ###########################"
		mkdir -p "$HOME/.config/openbox"
		cat "$myconfig/rc.xml" > "$HOME/.config/openbox/lxde-rc.xml"
	msg "######################## End Openbox ##########################"
fi

if confirm "Set openbox "; then
	msg "########################## Openbox ###########################"
		sudo cp /etc/xdg/openbox/autostart "$HOME/.config/openbox"
		chown "$USER":"$USER" "$HOME/.config/openbox/autostart"
		cat "$myconfig/openbox_autostart" >> "$HOME/.config/openbox/autostart"
	msg "######################## End Openbox ##########################"
fi

if confirm "Set .gitconfig"; then
	msg "############################ Git #############################"
	echo "Username"; read username
	echo "Mail"; read mail
	msg "Make .gitconfig"
		sed 's/defaultusername/'"$username"'/g;s/defaultmail/'"$mail"'/g' "${myconfig}"gitconfig > "$HOME/.gitconfig"
	msg "########################## End Git ###########################"
fi

if confirm "Set timezone"; then
	msg "######################### timezone ###########################"
		sudo dpkg-reconfigure tzdata
	msg "####################### end timezone #########################"
fi

if confirm "Downloads theme" ; then
	mkdir -p "$HOME/.themes"
	wget -P "$PWD/downloads" http://fc04.deviantart.net/fs70/f/2010/231/b/e/bumheadtrois_openbox_theme_by_1bumnote.zip
	file-roller -e "$HOME/.themes" "$PWD/downloads/bumheadtrois_openbox_theme_by_1bumnote.zip"
fi

if confirm "Downloads Icons"; then
	mkdir -p "$HOME/.icons"
	wget --content-disposition -P "$PWD/downloads" http://ubuntuone.com/2PCEQoHYUchMck1vxAtAC9
	file-roller -e "$HOME/.icons" "$PWD/downloads/Square.tar.gz"
fi

if confirm "Downloads Sublime Text 3"; then
	wget -P "$PWD/downloads" http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3059_amd64.deb
	sudo dpkg -i "$PWD/downloads/sublime-text_build-3059_amd64.deb"
fi


if confirm "Set autostart LXDE"; then
	mkdir -p "$HOME/.config/autostart"
	cp -R -t "$HOME/.config/autostart" "$myconfig/autostart" 
fi